---
editor_options: 
  markdown: 
    wrap: 72
---

# **Discussion** {#sec-discussion}

```{=html}
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-LKV6J2QECN"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-LKV6J2QECN');
</script>
```
#### Vegetable soybeans: origin, genetics, breeding importance {.unnumbered}

Vegetable soybeans, prized for their notable attributes such as large
seed size, sweetness, and lack of beany flavor, offer significant
nutritional advantages as a vegetable (Carneiro et al. 2020; Kumar et
al. 2011; Nair et al. 2023). Understanding their origin, genetic
structure, and selection signatures is pivotal for harnessing soybean
germplasms in breeding programs. In this study, we integrated phenotypic
and genotypic data to establish a core collection from 2,394 Taiwanese
soybean accessions. This core collection comprises 244 accessions from
29 countries, preserving over 98% of the allelic coverage. Compared to
previous collections based solely on phenotypic traits (Huang et al.
2022; Kao et al. 2021), our approach retains a more diverse germplasm at
the molecular level. The inclusion of these diverse accessions enhances
our understanding of the interplay between soybean phenomic and genomic
characteristics, providing a comprehensive foundation for future
breeding efforts.

#### Breeding goals and genetic diversity in soybeans {.unnumbered}

Compared to the broader objectives of grain soybeans, such as oil
production, animal feed, and human consumption, breeding goals for
vegetable soybeans are more specialized (Guo et al. 2022; Nair et al.
2023; Sedivy et al. 2017), resulting in lower variations
(Shanmugasundaram and Yan 2001). Previous breeding efforts in Taiwan
have utilized grain soybean germplasms to broaden genetic diversity and
enhance adaptation and resistance to biotic and abiotic stresses in
vegetable soybeans (Chou 2015; Shanmugasundaram and Yan 2001). Our
results reflect this breeding strategy, revealing a small proportion of
vegetable soybean accessions sharing genetic backgrounds with grain
soybeans (**Supplementary Tables 3 and 9**). Understanding these genetic
relationships informs breeding strategies aimed at enhancing desired
traits while preserving genetic diversity. The distinct genetic profiles
observed in vegetable soybeans compared to grain soybeans indicate the
importance of considering population structure and genetic diversity in
soybean breeding programs. While grain soybeans exhibited dispersed
distributions across multiple groups, vegetable soybeans (Group I)
exhibited a more specialized genetic profile with lower diversity and
increased differentiation from other groups, suggesting a specialized
genetic foundation shaped by breeding practices (**Fig. 4A-B**). AMOVA
results confirm the distinct genetic profiles between vegetable and
grain soybeans (**Fig. 4F**). The slower LD decay rates observed in
vegetable soybeans further imply a history of more selective processes
compared to grain soybeans (**Fig. 4D**), consistent with previous
studies (Liu et al. 2022).

#### Genomic scan identifies selection regions {.unnumbered}

To deepen our understanding of the genetic mechanisms underlying
vegetable soybean selection, we conducted a comprehensive genome-wide
scan and identified 159 significant signatures within 67 putative
selection regions (**Fig. 5**). The detection of favorable alleles in
vegetable soybeans (Group I), associated with a notable increase in
100-seed weight (**Fig. 6C**), highlights the effectiveness of
domestication and improvement efforts. Soybean is a short-day sensitive
plant, where flowering time and seed size play crucial roles in
determining seed yield (Vogel et al. 2021; Xiong et al. 2023; Zhang et
al. 2015). Our investigation pinpointed two chromosomal regions with
high selective signals (**Fig. 5B-C**), harboring *GmXXXX* and *GmXXXX*.
*GmXXXX* encodes a protein with the APETALA2 (AP2) domain, governing
floral, ovule, and seed development (Jiang et al. 2020; Yu et al. 2023).
Over-expression of *GmXXXX* in Arabidopsis results in significant
alterations in seed characteristics, impacting seed size and morphology
(Jiang et al. 2020). Recent research has further demonstrated the
co-regulatory mechanisms of *GmXXXX*and *GmXXXX* under short-day
conditions, jointly modulating photoperiodic regulation and influencing
seed size (Yu et al. 2023). Additionally, stem growth habit in soybeans
profoundly influences the reproductive period and seed development (Liu
et al. 2010; Xiong et al. 2023; Zhang et al. 2015). *GmXXXX* (*XXX*
locus), an *Arabidopsis XXX* (*AtXXX*) homolog, is a major regulator of
soybean determinacy (Liu et al. 2010). Determinate cultivars
(*dt1*/*dt1*) exhibit prompt stem termination post-flowering, while
indeterminate cultivars (*Dt1*/*Dt1*) sustain growth, leading to
extended flowering periods. Cultivars with minimal temporal overlap
between vegetative and reproductive phases have the potential to enhance
pod and seed development (Xiong et al. 2023). Furthermore, a genomic
association network study reveals the significant impact of the *XXX*
locus on various soybean traits, such as stem pod density, number of
three seeds per pod, and total seed number (Fang et al. 2017),
elucidating the roles of *GmXXXX* and *GmXXXX* in seed development and
reinforcing their importance in emphasizing the reproductive growth of
vegetable soybeans.

Furthermore, we identified overlaps between selection regions in
vegetable soybean and previously reported GWAS QTLs influencing key
agronomic traits (**Fig. 6A**). The convergence may indicate regions of
the genome under selective pressure due to their association with
crucial agronomic traits. For instance, selection region 14-3 aligns
with traits related to 100 pod fresh weight and 100 seed fresh weight
(Li et al. 2019). This evidence further underscores that the identified
selection regions are of interest for vegetable soybean improvement,
particularly in enhancing seed size and weight. In addition, selection
region 1-1 is associated with seed coat color, while regions 19-5 and
19-6 are linked to leaflet width and area (Fang et al. 2017). To meet
market preferences, vegetable soybeans are typically green or
yellow-green, unlike the varied colors observed in grain soybeans (Nair
et al. 2023; Sedivy et al. 2017). Previous studies have highlighted
variations in leaflet morphology, correlating with differences in seed
size and seed number per pod (Jeong et al. 2011). Thus, in breeding
efforts for vegetable soybeans, genomic regions associated with both
‘seed coat color’ and ‘leaflet-related traits’ may have been
specifically targeted, further emphasizing the importance of these
genomic regions in breeding programs aimed at improving vegetable
soybean cultivars.

#### Core collection optimizes germplasm analysis {.unnumbered}

Our study highlights the effectiveness of the core collection framework
for analyzing large-scale crop germplasm data, ensuring that observed
genetic variations accurately reflect true genetic diversity rather than
sampling biases. By reducing the number of accessions to manage and
maintain, core collections optimize resource allocation in efficient
utilization, germplasm-related research, and conservation efforts.
Through exploring population structure and genome-wide selection scans
within a diverse panel of soybean germplasm genomes, we identified loci
showing significant differences between vegetable and grain soybeans.
Validating core collection results against a larger population enhances
the credibility of this approach, offering a practical and
resource-efficient strategy for researchers handling extensive germplasm
datasets. The positive and significant correlation observed between
accumulated favorable alleles and 100-seed weight supports their
contribution to observed phenotypic variation (**Fig. 7A-B**),
highlighting the genetic basis of seed weight and the potential for
marker-assisted selection in yield improvement breeding programs. The
robustness of the core collection framework in identifying significant
genomic regions further sheds light on its utility in advancing genetic
studies and accelerating crop improvement efforts.

#### Limitations and future directions {.unnumbered}

While our study offers valuable insights into the genetic underpinnings
of vegetable soybean selection, it is essential to acknowledge
limitations that may constrain the generalizability and practicality of
our findings. Firstly, although our core collection is extensive, it may
not fully represent the global diversity of soybeans. Despite efforts to
include accessions from 29 countries, limitations in germplasms may
result in overlooked or underrepresented genetic variations,
particularly from regions not covered in this study. This could impact
the generalizability of the study findings to the broader vegetable
soybean population. Additionally, our focus on specific trait, may bias
the overall genetic variations, neglecting other potentially significant
genomic regions related associated with agronomic traits. Future studies
could broaden the scope of phenogenomic analysis to encompass a broader
range of agronomic traits and provide a more comprehensive understanding
of the genetic basis of vegetable soybean adaptation and resilience to
environmental challenges. Finally, our reliance on historical data and
existing germplasm collections may not fully capture the dynamic
evolution of soybean genetics in response to changing environmental
conditions and emerging challenges (Singer et al. 2023). Despite these
constraints, our study serves as a stepping stone for further research
and underscores the importance of the ongoing need to explore and
incorporate diverse genetic resources to unravel the complexities of
vegetable soybean genetics and advance breeding endeavors.

#### Conclusion {.unnumbered}

In conclusion, our investigation on vegetable soybeans reveals distinct
genetic profiles compared to grain soybeans, emphasizing the importance
of targeted breeding efforts aimed at specific traits such as seed size
and weight. The establishment of a diverse core collection, integrating
phenotypic and genotypic data, enriches our understanding of soybean
characteristics. We identified significant selection signatures and
potential selection regions associated with vegetable soybean
improvement, highlighting candidate genes crucial for seed development
and flowering time regulation. The positive correlation between
favorable alleles and 100-seed weight emphasizes the potential for the
breeding program. Overall, within the framework of the core collection,
our study contributes to a deep understanding of the genetic basis of
vegetable soybean selection, offering valuable insights for further
functional investigations and the advancement of improvement efforts.
